[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/projects/*"
  to = "/projects/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*" 
